# Model arguments
model_name_or_path: Qwen/Qwen2.5-Math-1.5B
model_revision: main
#torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: DigitalLearningGmbH/MATH-lighteval
dataset_config: default
dataset_prompt_column: problem
chat_template: |
  {#- This block extracts the system message, so we can slot it into the right place. #}
  {%- if messages[0]['role'] == 'system' %}
      {%- set system_message = messages[0]['content']|trim %}
      {%- set messages = messages[1:] %}
  {%- else %}
      {%- set system_message = "" %}
  {%- endif %}

  {%- for message in messages %}
      {{- 'Question:' + '\n' +  message['content'] + '\n' }}
  {%- endfor %}
  {%- if add_generation_prompt %}
      {{- 'Answer:' + '\n' + "Let's think step by step." + '\n' }}
  {%- endif %}


eval_dataset_names:
- math500
#- aime24
#- aime25
#- amc
#- minerva
#- olympiad
#- aime24_avg8
#- aime25_avg8
#- amc_avg8

# GRPO trainer config
bf16: true
use_vllm: true
vllm_gpu_memory_utilization: 0.4
do_eval: true
eval_strategy: steps
eval_steps: 10
gradient_accumulation_steps: 16
steps_per_generation: 64
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: qwen2.5-math-1.5b-adamw-lr1e6
hub_strategy: every_save
learning_rate: 1.0e-06
log_completions: false
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: constant
max_prompt_length: 1024
max_completion_length: 3072
max_steps: -1
num_generations: 16
num_train_epochs: 3
output_dir: data/qwen2.5-math-1.5b-adamw-lr1e6-blue
overwrite_output_dir: true
per_device_eval_batch_size: 64
per_device_train_batch_size: 2
push_to_hub: false
report_to:
- wandb
reward_funcs:
- boxed_accuracy
reward_weights:
- 1.0
save_strategy: "epoch"
save_total_limit: 3
seed: 42
eval_on_start: true
