# Model arguments
model_name_or_path: meta-llama/Llama-3.2-3B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: DigitalLearningGmbH/MATH-lighteval
dataset_config: default
dataset_prompt_column: problem
chat_template: |
  {{- bos_token }}

  {#- This block extracts the system message, so we can slot it into the right place. #}
  {%- if messages[0]['role'] == 'system' %}
      {%- set system_message = messages[0]['content']|trim %}
      {%- set messages = messages[1:] %}
  {%- else %}
      {%- set system_message = "" %}
  {%- endif %}

  {#- System message #}
  {{- "<|start_header_id|>system<|end_header_id|>\n\n" }}
  {{- system_message }}
  {{- "<|eot_id|>" }}

  {%- for message in messages %}
      {{- '<|start_header_id|>' + message['role'] + '<|end_header_id|>\n\n'+ (message['content'] | trim) + '\n' + 'Please reason step by step, and put your final answer within \\boxed{}.' + '<|eot_id|>' }}
  {%- endfor %}
  {%- if add_generation_prompt %}
      {{- '<|start_header_id|>assistant<|end_header_id|>\n\n' }}
  {%- endif %}



system_prompt: "You are a helpful assistant."
eval_dataset_names:
- math500

# GRPO trainer config
bf16: true
use_vllm: true
do_eval: true
eval_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 32
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Llama-3.2-3B-Open-R1-GRPO
vllm_gpu_memory_utilization: 0.9
hub_strategy: every_save
learning_rate: 1.0e-6
log_completions: false
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 512
max_completion_length: 1024
max_steps: -1
num_generations: 16
num_train_epochs: 1
output_dir: data/Llama-3.2-3B-Open-R1-GRPO
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 2
push_to_hub: false
report_to:
- wandb
reward_funcs:
- boxed_accuracy
reward_weights:
- 1.0
save_strategy: "epoch"
save_total_limit: 1
seed: 42
warmup_ratio: 0.1
eval_on_start: true
